[package]
name = "bc-algo"
version = "0.1.0"
authors = ["fanhui <hui.fan@mail.ru>"]
edition = "2018"

[dependencies]
error-chain = "0.12.0"
ring = "0.14.3"
rayon = "1.0.3"
lazy_static = "1.2.0"

[dev-dependencies]
rand = "0.6.4"
